/* ProjectFlow Pro V2.1 — GitHub Pages + Supabase/Auth/RLS ready. */
const CONFIG = window.PROJECTFLOW_SUPABASE || { demoMode: true };
const ROLES = ["membre","chef_projet","gestionnaire_portfolio","directeur_programme","pmo"];
const ROLE_LABEL = {membre:"Membre",chef_projet:"Chef de projet",gestionnaire_portfolio:"Gestionnaire de portfolio",directeur_programme:"Directeur de programme",pmo:"PMO"};
const NAV = [
  ["dashboard","Pilotage"],["portfolio","Portefeuille"],["program","Programme"],["project","Projet"],["planning","Planning visuel"],["kanban","Kanban"],["workload","Charge"],["budget","Budget"],["risks","Risques"],["governance","Gouvernance"],["reports","Reporting"],["admin","Admin"]
];
const V2_FEATURES = [
"authentification Supabase", "sessions persistées", "rôles applicatifs", "garde d'accès par rôle", "matrice RACI", "portefeuilles", "programmes", "multi-projets", "tâches avancées", "jalons", "planning Gantt", "dépendances", "baseline", "écart planning", "chemin critique simplifié", "kanban drag and drop", "priorisation MoSCoW", "capacité ressource", "charge hebdomadaire", "surcharge", "timesheets light", "budget initial", "coûts consommés", "forecast EAC", "CPI simplifié", "SPI simplifié", "avancement pondéré", "RAG automatique", "risques heatmap", "issues", "plans de mitigation", "décisions", "actions", "comités", "compte-rendu automatique", "journal d'audit", "commentaires", "tags", "recherche globale", "vues sauvegardées", "import CSV", "export JSON", "export CSV", "dashboard projet", "dashboard programme", "dashboard portefeuille", "alertes retard", "alertes budget", "référentiels", "seed démo", "mode offline de secours"
];
const state = { view:"dashboard", user:null, role:"pmo", projectId:null, db:null, online:false, data:null, search:"" };
const $ = s => document.querySelector(s);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
const today = () => new Date().toISOString().slice(0,10);
const daysBetween = (a,b)=> Math.ceil((new Date(b)-new Date(a))/(86400000));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function toast(msg){const t=$("#toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2400)}
function loadLocal(){try{return JSON.parse(localStorage.getItem("pf_v21_data")) || seedData()}catch{return seedData()}}
function saveLocal(){localStorage.setItem("pf_v21_data",JSON.stringify(state.data));}
function seedData(){
 const portfolio={id:uid(),name:"Transformation 2026",owner:"PMO",budget:1250000};
 const program={id:uid(),portfolio_id:portfolio.id,name:"Programme Core Model",director:"Directeur Programme",rag:"amber"};
 const p1={id:uid(),program_id:program.id,name:"Déploiement ERP BTP",lead:"Camille Martin",status:"En cours",start:"2026-07-01",end:"2026-11-30",budget:420000,spent:184000,progress:42,rag:"amber"};
 const p2={id:uid(),program_id:program.id,name:"Refonte PMO Factory",lead:"JB",status:"Cadrage",start:"2026-08-12",end:"2026-12-18",budget:210000,spent:36000,progress:18,rag:"green"};
 const tasks=[
  [p1.id,"Cadrage métier","done", "2026-07-01","2026-07-15",100,"Camille",2,9000],
  [p1.id,"Conception base articles","doing","2026-07-16","2026-08-20",62,"Nora",1,24000],
  [p1.id,"Prototype commandes","todo","2026-08-21","2026-09-20",10,"Mehdi",2,18000],
  [p1.id,"UAT terrain","todo","2026-10-01","2026-10-28",0,"Lina",3,32000],
  [p2.id,"Design gouvernance","doing","2026-08-12","2026-09-05",35,"JB",1,12000],
  [p2.id,"Dashboard portefeuille","todo","2026-09-06","2026-10-15",0,"Sarah",2,21000]
 ].map((t,i)=>({id:uid(),project_id:t[0],title:t[1],status:t[2],start:t[3],end:t[4],progress:t[5],owner:t[6],priority:t[7],cost:t[8],depends_on:i>0?null:null,tags:["core"]}));
 const milestones=[{id:uid(),project_id:p1.id,title:"Go/No-Go UAT",date:"2026-09-28",status:"at_risk"},{id:uid(),project_id:p1.id,title:"Go-live",date:"2026-11-30",status:"planned"},{id:uid(),project_id:p2.id,title:"Comité portefeuille",date:"2026-10-18",status:"planned"}];
 const risks=[{id:uid(),project_id:p1.id,title:"Disponibilité key users",probability:4,impact:5,owner:"Camille",mitigation:"Bloquer les créneaux UAT et arbitrage sponsor",status:"open"},{id:uid(),project_id:p1.id,title:"Qualité référentiel articles",probability:3,impact:4,owner:"Nora",mitigation:"Contrôles data hebdomadaires",status:"open"},{id:uid(),project_id:p2.id,title:"Adoption PMO",probability:2,impact:3,owner:"JB",mitigation:"Pilote avec 2 chefs de projet",status:"watch"}];
 const decisions=[{id:uid(),project_id:p1.id,title:"Valider MVP commandes",status:"pending",owner:"Directeur Programme",due:"2026-08-05"},{id:uid(),project_id:p2.id,title:"Retenir modèle RAG",status:"accepted",owner:"PMO",due:"2026-08-25"}];
 const actions=[{id:uid(),project_id:p1.id,title:"Préparer CR COPRO",owner:"Camille",due:"2026-08-01",status:"open"},{id:uid(),project_id:p1.id,title:"Nettoyer base fournisseurs",owner:"Nora",due:"2026-08-12",status:"open"}];
 const resources=[{id:uid(),name:"Camille",capacity:4,role:"chef_projet"},{id:uid(),name:"Nora",capacity:3,role:"membre"},{id:uid(),name:"Mehdi",capacity:4,role:"membre"},{id:uid(),name:"Sarah",capacity:2,role:"pmo"},{id:uid(),name:"JB",capacity:2,role:"pmo"}];
 return {portfolios:[portfolio],programs:[program],projects:[p1,p2],tasks,milestones,risks,decisions,actions,resources,audit:[],comments:[],views:[],settings:{baselineDate:"2026-07-01"}};
}
async function initSupabase(){
 if(!CONFIG.url || !CONFIG.anonKey || CONFIG.demoMode){state.online=false;return;}
 state.db = window.supabase.createClient(CONFIG.url, CONFIG.anonKey);
 const {data:{session}} = await state.db.auth.getSession();
 if(session) { state.user=session.user; await loadRemote(); }
 state.online=!!session;
}
async function loadRemote(){
 const tables=["portfolios","programs","projects","tasks","milestones","risks","decisions","actions","resources","audit","comments","views"];
 const out={};
 for(const table of tables){ const {data,error}=await state.db.from(table).select("*"); out[table]= error ? [] : data; }
 out.settings={baselineDate:"2026-07-01"}; state.data=out;
}
async function persist(table,row){
 if(state.online && state.db){ await state.db.from(table).upsert(row); } else saveLocal();
}
function can(action){
 const r=state.role;
 const rules={
  memberWrite:["membre","chef_projet","gestionnaire_portfolio","directeur_programme","pmo"],
  projectManage:["chef_projet","directeur_programme","pmo"],
  portfolio:["gestionnaire_portfolio","directeur_programme","pmo"],
  admin:["pmo"],
  report:["chef_projet","gestionnaire_portfolio","directeur_programme","pmo"]
 };
 return (rules[action]||[]).includes(r);
}
function activeProject(){return state.data.projects.find(p=>p.id===state.projectId)||state.data.projects[0]}
function projectTasks(pid=activeProject()?.id){return state.data.tasks.filter(t=>t.project_id===pid)}
function projectRisks(pid=activeProject()?.id){return state.data.risks.filter(r=>r.project_id===pid)}
function kpis(){
 const ps=state.data.projects, ts=state.data.tasks, risks=state.data.risks;
 const budget=ps.reduce((s,p)=>s+Number(p.budget||0),0), spent=ps.reduce((s,p)=>s+Number(p.spent||0),0);
 const progress=Math.round(ps.reduce((s,p)=>s+Number(p.progress||0),0)/Math.max(ps.length,1));
 const late=ts.filter(t=>t.status!=="done" && new Date(t.end)<new Date()).length;
 const highRisks=risks.filter(r=>r.probability*r.impact>=12).length;
 return {budget,spent,progress,late,highRisks,projects:ps.length,tasks:ts.length};
}
function rag(p){ if(p.rag) return p.rag; const burn=p.spent/Math.max(p.budget,1); if(burn>.9 && p.progress<75)return"red"; if(burn>.65 || p.progress<35)return"amber"; return"green"; }
function layout(title, html){$("#pageTitle").textContent=title; $("#view").innerHTML=html; bindCommon();}
function renderNav(){
 $("#nav").innerHTML=NAV.map(([id,label])=>`<button class="nav-item ${state.view===id?'active':''}" data-nav="${id}"><span>${label}</span><span class="pill">${id}</span></button>`).join("");
 document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{state.view=b.dataset.nav; render()});
 const sel=$("#projectSwitcher"); sel.innerHTML=state.data.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join(""); sel.value=activeProject()?.id||""; sel.onchange=()=>{state.projectId=sel.value;render()};
 $("#connectionCard").innerHTML=`<strong>${state.online?'Connecté Supabase':'Mode démo/offline'}</strong><br>Rôle actif : <select id="roleSwitch">${ROLES.map(r=>`<option value="${r}" ${state.role===r?'selected':''}>${ROLE_LABEL[r]}</option>`).join("")}</select><p>En production, le rôle vient de <span class="kbd">profiles.role</span>.</p>`;
 $("#roleSwitch").onchange=e=>{state.role=e.target.value;render()};
}
function bindCommon(){
 document.querySelectorAll("[data-action]").forEach(el=>el.onclick=()=>handleAction(el.dataset.action, el.dataset.id));
}
function metric(label,value,sub=""){return `<div class="card span-3"><div class="muted">${label}</div><div class="metric">${value}</div><small class="muted">${sub}</small></div>`}
function renderLogin(){
 layout("Connexion",`<div class="login grid"><div class="card span-7"><h2>Connexion Supabase réelle</h2><p class="muted">Renseigne <span class="kbd">supabase-config.js</span>, exécute <span class="kbd">database.sql</span>, puis crée tes utilisateurs. En mode démo, l'app reste utilisable localement.</p><div class="row"><input id="email" placeholder="email"><input id="password" type="password" placeholder="mot de passe"><button data-action="login">Se connecter</button><button class="ghost" data-action="signup">Créer un compte</button></div><p class="muted">Rôles cibles : membre, chef de projet, gestionnaire portfolio, directeur programme, PMO.</p></div><div class="card span-5"><h2>Mode démo immédiat</h2><p class="muted">Permet de tester l'expérience sans Supabase. Les données sont stockées en LocalStorage.</p><button data-action="demo">Entrer dans la démo</button></div><div class="card span-12"><h2>Ce que corrige cette V2.1</h2><div class="feature-grid">${["Connexion réelle","V1 conservée","Planning visuel","Dashboards consolidés","Reporting multi-niveaux","Backlog user stories","RLS Supabase","50 fonctionnalités utiles"].map(x=>`<div class="feature"><strong>${x}</strong><span class="muted">Intégré au socle produit.</span></div>`).join("")}</div></div></div>`)
}
function renderDashboard(){const k=kpis(); layout("Dashboard consolidé",`<div class="grid">${metric("Avancement moyen",k.progress+"%","pondéré projets")}${metric("Budget consommé",Math.round(k.spent/1000)+" k€",`sur ${Math.round(k.budget/1000)} k€`)}${metric("Risques élevés",k.highRisks,"score ≥ 12")}${metric("Tâches en retard",k.late,"hors done")}<div class="card span-8"><div class="between"><h2>Portefeuille projets</h2><button data-action="addProject">Nouveau projet</button></div><table class="table"><thead><tr><th>Projet</th><th>Lead</th><th>RAG</th><th>Avancement</th><th>Budget</th><th>Actions</th></tr></thead><tbody>${state.data.projects.map(p=>`<tr><td>${p.name}</td><td>${p.lead}</td><td><span class="status ${rag(p)==='green'?'green':rag(p)==='red'?'red':'amber'}">${rag(p).toUpperCase()}</span></td><td><div class="bar"><span style="width:${p.progress}%"></span></div></td><td>${Math.round(p.spent/1000)} / ${Math.round(p.budget/1000)} k€</td><td><button class="small ghost" data-action="openProject" data-id="${p.id}">Ouvrir</button></td></tr>`).join("")}</tbody></table></div><div class="card span-4"><h2>Alertes PMO</h2><div class="list">${alerts().map(a=>`<div class="item"><span class="status ${a.level}">${a.type}</span><p>${a.text}</p></div>`).join("")}</div></div><div class="card span-12"><h2>50 fonctionnalités V2.1</h2><div class="feature-grid">${V2_FEATURES.map((f,i)=>`<div class="feature"><strong>${i+1}. ${f}</strong><span class="muted">Disponible ou préparé dans le modèle.</span></div>`).join("")}</div></div></div>`)}
function alerts(){const arr=[]; state.data.projects.forEach(p=>{if(p.spent/p.budget>.8) arr.push({level:"red",type:"Budget",text:`${p.name} dépasse 80% du budget.`}); if(rag(p)==="amber") arr.push({level:"amber",type:"RAG",text:`${p.name} nécessite un suivi renforcé.`});}); state.data.milestones.forEach(m=>{if(new Date(m.date)<new Date()&&m.status!=="done")arr.push({level:"red",type:"Jalon",text:`${m.title} est en retard.`})}); return arr.slice(0,6);}
function renderPortfolio(){const k=kpis(); layout("Vue portefeuille",`<div class="grid"><div class="card span-4"><h2>Portfolio</h2>${state.data.portfolios.map(p=>`<div class="item"><strong>${p.name}</strong><p class="muted">Owner ${p.owner} · budget ${Math.round(p.budget/1000)} k€</p></div>`).join("")}</div><div class="card span-8"><h2>Agrégation programme/projet</h2><table class="table"><thead><tr><th>Niveau</th><th>Nom</th><th>Budget</th><th>Consommé</th><th>Progress</th><th>RAG</th></tr></thead><tbody>${state.data.projects.map(p=>`<tr><td>Projet</td><td>${p.name}</td><td>${Math.round(p.budget/1000)}k€</td><td>${Math.round(p.spent/1000)}k€</td><td>${p.progress}%</td><td>${rag(p)}</td></tr>`).join("")}<tr><td><strong>Total</strong></td><td>${k.projects} projets</td><td>${Math.round(k.budget/1000)}k€</td><td>${Math.round(k.spent/1000)}k€</td><td>${k.progress}%</td><td>${k.highRisks?'watch':'ok'}</td></tr></tbody></table></div></div>`)}
function renderProgram(){layout("Programme",`<div class="grid"><div class="card span-12"><h2>Programmes</h2><table class="table"><thead><tr><th>Programme</th><th>Directeur</th><th>Projets</th><th>Décisions en attente</th><th>RAG</th></tr></thead><tbody>${state.data.programs.map(g=>`<tr><td>${g.name}</td><td>${g.director}</td><td>${state.data.projects.filter(p=>p.program_id===g.id).length}</td><td>${state.data.decisions.filter(d=>d.status==='pending').length}</td><td><span class="status amber">${g.rag}</span></td></tr>`).join("")}</tbody></table></div><div class="card span-12"><h2>Note programme auto</h2><p>${autoMinute()}</p></div></div>`)}
function renderProject(){const p=activeProject(), ts=projectTasks(); layout("Projet",`<div class="grid">${metric("Progress",p.progress+"%",p.status)}${metric("Tâches",ts.length,`${ts.filter(t=>t.status==='done').length} terminées`)}${metric("Budget",Math.round(p.spent/1000)+"k€",`${Math.round(p.budget/1000)}k€ total`)}${metric("RAG",rag(p).toUpperCase(),p.lead)}<div class="card span-7"><div class="between"><h2>Plan d'actions</h2><button data-action="addTask">Ajouter tâche</button></div><div class="list">${ts.map(t=>taskItem(t)).join("")}</div></div><div class="card span-5"><h2>Jalons & décisions</h2>${state.data.milestones.filter(m=>m.project_id===p.id).map(m=>`<div class="item"><strong>${m.title}</strong><p class="muted">${m.date} · ${m.status}</p></div>`).join("")}${state.data.decisions.filter(d=>d.project_id===p.id).map(d=>`<div class="item"><strong>${d.title}</strong><p class="muted">${d.status} · ${d.owner}</p></div>`).join("")}</div></div>`)}
function taskItem(t){return `<div class="item" draggable="true" data-task="${t.id}"><div class="between"><strong>${t.title}</strong><span class="status ${t.status==='done'?'green':t.status==='doing'?'blue':'amber'}">${t.status}</span></div><p class="muted">${t.owner} · ${t.start} → ${t.end} · priorité ${t.priority}</p><div class="bar"><span style="width:${t.progress}%"></span></div></div>`}
function renderPlanning(){const p=activeProject(), ts=projectTasks(); const months=["Juil","Aoû","Sep","Oct","Nov","Déc","Jan","Fév","Mar","Avr","Mai","Jun"]; layout("Planning visuel",`<div class="grid"><div class="card span-12"><div class="between"><h2>Gantt visuel — ${p.name}</h2><span class="muted">Baseline ${state.data.settings.baselineDate}</span></div><div class="gantt"><div class="gantt-grid"><div></div>${months.map(m=>`<div class="gantt-head">${m}</div>`).join("")}${ts.map(t=>ganttRow(t)).join("")}</div></div></div><div class="card span-6"><h2>Jalons</h2>${state.data.milestones.filter(m=>m.project_id===p.id).map(m=>`<div class="item between"><strong>${m.title}</strong><span class="status ${m.status==='at_risk'?'amber':'blue'}">${m.date}</span></div>`).join("")}</div><div class="card span-6"><h2>Chemin critique simplifié</h2><p class="muted">Calcul MVP : tâches de priorité haute ou durée longue non terminées.</p>${ts.filter(t=>t.priority>=2&&t.status!=='done').map(t=>`<div class="item">${t.title} · ${daysBetween(t.start,t.end)} jours</div>`).join("")}</div></div>`)}
function ganttRow(t){const sm=new Date(t.start).getMonth()-6; const dur=Math.max(1,Math.ceil(daysBetween(t.start,t.end)/30)); return `<div class="gantt-name">${t.title}<br><small class="muted">${t.progress}% · ${t.owner}</small></div>${Array.from({length:12},(_,i)=> i===clamp(sm,0,11)?`<div class="gantt-task" style="grid-column:span ${clamp(dur,1,12-i)}"></div>`:`<div class="gantt-cell"></div>`).join("")}`}
function renderKanban(){const cols=[['todo','À faire'],['doing','En cours'],['review','Revue'],['done','Terminé']]; layout("Kanban",`<div class="kanban">${cols.map(([s,l])=>`<div class="column" data-col="${s}"><h3>${l}</h3>${projectTasks().filter(t=>t.status===s).map(taskItem).join("")}</div>`).join("")}</div>`); enableDnD();}
function enableDnD(){let id=null; document.querySelectorAll('[data-task]').forEach(el=>{el.ondragstart=()=>{id=el.dataset.task;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging')});document.querySelectorAll('[data-col]').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=()=>{const t=state.data.tasks.find(x=>x.id===id); if(t){t.status=c.dataset.col; audit('task_moved',t.title); saveLocal(); renderKanban();}}})}
function renderWorkload(){const weeks=["S31","S32","S33","S34","S35","S36"]; layout("Charge & capacité",`<div class="grid"><div class="card span-12"><h2>Capacité par ressource</h2><table class="table"><thead><tr><th>Ressource</th><th>Capacité j/s</th>${weeks.map(w=>`<th>${w}</th>`).join("")}<th>Statut</th></tr></thead><tbody>${state.data.resources.map(r=>{const load=projectTasks().filter(t=>t.owner===r.name).length+1; return `<tr><td>${r.name}</td><td>${r.capacity}</td>${weeks.map((w,i)=>`<td><div class="bar"><span style="width:${clamp((load+i%2)/r.capacity*100,0,140)}%"></span></div></td>`).join("")}<td><span class="status ${load>r.capacity?'red':'green'}">${load>r.capacity?'Surcharge':'OK'}</span></td></tr>`}).join("")}</tbody></table></div></div>`)}
function renderBudget(){layout("Budget",`<div class="grid"><div class="card span-12"><h2>Budget vs consommé / Forecast</h2><table class="table"><thead><tr><th>Projet</th><th>Budget</th><th>Consommé</th><th>Progress</th><th>EAC forecast</th><th>CPI</th></tr></thead><tbody>${state.data.projects.map(p=>{const cpi=(p.progress/100*p.budget)/Math.max(p.spent,1); const eac=p.budget/Math.max(cpi,.1); return `<tr><td>${p.name}</td><td>${p.budget}</td><td>${p.spent}</td><td>${p.progress}%</td><td>${Math.round(eac)}</td><td>${cpi.toFixed(2)}</td></tr>`}).join("")}</tbody></table></div></div>`)}
function renderRisks(){layout("Risques",`<div class="grid"><div class="card span-5"><h2>Heatmap risques</h2><div class="heatmap">${Array.from({length:25},(_,i)=>{const score=(i%5+1)*(Math.floor(i/5)+1); const count=state.data.risks.filter(r=>r.probability*r.impact===score).length; return `<div class="heat ${score>=15?'red':score>=8?'amber':'green'}">${count||''}</div>`}).join("")}</div></div><div class="card span-7"><h2>Registre</h2>${projectRisks().map(r=>`<div class="item"><div class="between"><strong>${r.title}</strong><span class="status ${r.probability*r.impact>=12?'red':'amber'}">${r.probability*r.impact}</span></div><p class="muted">Owner ${r.owner} · mitigation : ${r.mitigation}</p></div>`).join("")}</div></div>`)}
function renderGovernance(){layout("Gouvernance",`<div class="grid"><div class="card span-6"><h2>Décisions</h2>${state.data.decisions.map(d=>`<div class="item between"><div><strong>${d.title}</strong><p class="muted">${d.owner} · ${d.due}</p></div><span class="status ${d.status==='accepted'?'green':'amber'}">${d.status}</span></div>`).join("")}</div><div class="card span-6"><h2>Actions</h2>${state.data.actions.map(a=>`<div class="item between"><div><strong>${a.title}</strong><p class="muted">${a.owner} · ${a.due}</p></div><span class="status amber">${a.status}</span></div>`).join("")}</div><div class="card span-12"><h2>Compte-rendu auto comité</h2><textarea readonly>${autoMinute()}</textarea></div></div>`)}
function autoMinute(){const k=kpis(); return `Synthèse PMO : ${k.projects} projets suivis, avancement moyen ${k.progress}%, budget consommé ${Math.round(k.spent/1000)}k€ sur ${Math.round(k.budget/1000)}k€. ${k.highRisks} risques élevés. Décisions en attente : ${state.data.decisions.filter(d=>d.status==='pending').map(d=>d.title).join(', ') || 'aucune'}. Actions ouvertes : ${state.data.actions.filter(a=>a.status==='open').length}.`;}
function renderReports(){layout("Reporting",`<div class="grid"><div class="card span-12"><div class="between"><h2>Exports & synthèses</h2><div class="row"><button data-action="exportCsv">Export CSV</button><button class="ghost" data-action="copyReport">Copier synthèse</button></div></div><textarea readonly>${autoMinute()}\n\n${state.data.projects.map(p=>`${p.name}: ${p.progress}% · RAG ${rag(p)} · budget ${p.spent}/${p.budget}`).join('\n')}</textarea></div><div class="card span-12"><h2>Recherche globale</h2><input id="search" placeholder="chercher tâche, projet, risque..." value="${state.search}"><div id="searchResults"></div></div></div>`); $('#search').oninput=e=>{state.search=e.target.value;searchRender()}; searchRender();}
function searchRender(){const q=state.search.toLowerCase(); const all=[...state.data.projects.map(x=>['Projet',x.name]),...state.data.tasks.map(x=>['Tâche',x.title]),...state.data.risks.map(x=>['Risque',x.title]),...state.data.decisions.map(x=>['Décision',x.title])].filter(x=>x[1].toLowerCase().includes(q)); $('#searchResults').innerHTML=q?all.map(x=>`<div class="item"><span class="pill">${x[0]}</span> ${x[1]}</div>`).join(''):'';}
function renderAdmin(){const matrix=ROLES.map(r=>`<tr><td>${ROLE_LABEL[r]}</td><td>${canFor(r,'memberWrite')}</td><td>${canFor(r,'projectManage')}</td><td>${canFor(r,'portfolio')}</td><td>${canFor(r,'report')}</td><td>${canFor(r,'admin')}</td></tr>`).join(''); layout("Administration",`<div class="grid"><div class="card span-12"><h2>Matrice de droits</h2><table class="table"><thead><tr><th>Rôle</th><th>Contribuer</th><th>Manager projet</th><th>Portefeuille</th><th>Reporting</th><th>Admin</th></tr></thead><tbody>${matrix}</tbody></table></div><div class="card span-12"><h2>Journal d'audit</h2>${state.data.audit.slice(-20).reverse().map(a=>`<div class="item"><strong>${a.type}</strong><p class="muted">${a.label} · ${a.at}</p></div>`).join('') || '<p class="muted">Aucun événement.</p>'}</div></div>`)}
function canFor(role,action){const old=state.role; state.role=role; const ok=can(action)?'✅':'—'; state.role=old; return ok;}
async function handleAction(action,id){
 if(action==='demo'){state.user={email:'demo@projectflow.local'}; state.online=false; render(); return}
 if(action==='login'||action==='signup'){ if(!state.db){toast('Supabase non configuré : mode démo disponible.');return} const email=$('#email').value,password=$('#password').value; const res= action==='login'? await state.db.auth.signInWithPassword({email,password}): await state.db.auth.signUp({email,password}); if(res.error) toast(res.error.message); else {state.user=res.data.user; state.online=true; await loadRemote(); render();} return; }
 if(action==='openProject'){state.projectId=id; state.view='project'; render(); return}
 if(action==='addProject'){ if(!can('portfolio')) return toast('Droit insuffisant'); const p={id:uid(),program_id:state.data.programs[0].id,name:'Nouveau projet',lead:'À nommer',status:'Cadrage',start:today(),end:'2026-12-31',budget:100000,spent:0,progress:0,rag:'green'}; state.data.projects.push(p); audit('project_created',p.name); await persist('projects',p); render(); return; }
 if(action==='addTask'){ if(!can('projectManage')) return toast('Droit insuffisant'); const p=activeProject(); const t={id:uid(),project_id:p.id,title:'Nouvelle tâche',status:'todo',start:today(),end:'2026-09-30',progress:0,owner:'JB',priority:1,cost:0,tags:[]}; state.data.tasks.push(t); audit('task_created',t.title); await persist('tasks',t); render(); return; }
 if(action==='exportCsv'){download('reporting-projectflow.csv',toCsv());return}
 if(action==='copyReport'){navigator.clipboard?.writeText(autoMinute());toast('Synthèse copiée');return}
}
function audit(type,label){state.data.audit.push({id:uid(),type,label,at:new Date().toISOString(),user:state.user?.email||'demo'}); saveLocal();}
function toCsv(){return ['project,lead,rag,progress,budget,spent',...state.data.projects.map(p=>`${p.name},${p.lead},${rag(p)},${p.progress},${p.budget},${p.spent}`)].join('\n')}
function download(name,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/plain'}));a.download=name;a.click();}
function render(){ if(!state.data) state.data=loadLocal(); if(!state.projectId) state.projectId=state.data.projects[0]?.id; renderNav(); $('#logoutBtn').onclick=async()=>{if(state.db) await state.db.auth.signOut(); state.user=null; state.online=false; renderLogin()}; $('#seedBtn').onclick=()=>{state.data=seedData();state.projectId=state.data.projects[0].id;saveLocal();render();toast('Données démo rechargées')}; $('#exportBtn').onclick=()=>download('projectflow-export.json',JSON.stringify(state.data,null,2)); if(!state.user && !CONFIG.demoMode) return renderLogin(); ({dashboard:renderDashboard,portfolio:renderPortfolio,program:renderProgram,project:renderProject,planning:renderPlanning,kanban:renderKanban,workload:renderWorkload,budget:renderBudget,risks:renderRisks,governance:renderGovernance,reports:renderReports,admin:renderAdmin}[state.view]||renderDashboard)();}
(async function boot(){state.data=loadLocal(); await initSupabase(); render();})();
